# Nombre que se mostrará en la pestaña "Actions" de tu repositorio de GitHub
name: CI
run-name: Deploy in live by ${{github.actor}}

# Define los "DISPARADORES" (triggers) que activan este flujo automáticamente
on:
  push:
    branches: [ "main" ]  # Se ejecuta cada vez que subes cambios (git push) a la rama main, tambien se puede - main o - feature/*
    # - main --> Tambien se puede asi sin [ "main" ]
    # - feature/* --> Todas las ramas que hagan algo mas.
      
  pull_request:
    branches:
    - main # Se ejecuta cuando alguien propone cambios hacia la rama main  
    paths:
        - "*.md" # No se dispare si hay cambios en en este fichero.  

  workflow_dispatch: # Se utiliza para ejecuciones manuales, debo estar ubicado en la rama correcta, no necesita atributos

#########################################################################################################

# Bloque que contiene los trabajos o tareas que va a realizar el servidor
jobs: # Estos Job se van a lanzar en diferentes servidores 
  job1: # Este nombre se le puede dar cualquiera build , demo, pepito, etc.
    runs-on: ubuntu-latest # Sistema operativo donde correra el software a subir (En este caso son maquinas Linux)
    steps: # Lista de pasos secuenciales que ejecutará el servidor de linux
    - name: checkout code  # Paso 1 Revisando Codigo,  Descarga una copia de todo el código de tu repositorio en el servidor virtual      
      uses: actions/checkout@v7 # Paso 2: checkout@v5 Clona y copia y te deja en el directorio, el uses busca un trozo de codigo que alguien ya ha echo e instala las herramientas de Visual Studio 
      # with:  con esto podemos seleccionar atributos directorio, si es privado el repo ssh...
       #  repository: Mois-sgv/pruebas-github-actions
    - name: Echo file
      run: cat hola.txt

    - name: Print Message #El (-) indica que es un steps (paso) Imprimo en pantalla un mensaje,       
      run:  |  # Lo imprimo, Run es para ejecutar un comando, para varios comandos usamos el pi | y si es una sola lo eliminamos, la instalacion es Linux. 
            echo "Hola, !" 
            echo "Buenas tardes "             
    - name: List directory # listar directorio en el servidor donde se han subido los ficheros       
      run:  ls -la       
   
           

  job2: # Este nombre se le puede dar cualquiera build , demo, pepito, etc.
    needs: job1 # [job1, job2, job3 ...] Esto indica que para que se ejecute el Job2 debe finalizar primero el job1
    runs-on: ubuntu-latest # Sistema operativo donde correra el software a subir (En este caso son maquinas Linux)
    steps: # Lista de pasos secuenciales que ejecutará el servidor de Linux
    - name: checkout code 
      uses: actions/checkout@v7  

    - name: Print Message # Imprimo en pantalla un mensaje,       
      run:  echo "Hola, job 2"

    - name: Echo file
      run: cat Estructura.txt

    - name: Echo file
      run: cat nota.txt
    
    - name: Echo SECRETOS
      run: echo "${{ secrets.SECRETO }}" > secreto.txt
  
  job3: 
    needs: job1
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout code 
      uses: actions/checkout@v7  

    - name: Echo SECRETOS # trabajando con secretos a nivel de repositorio y enviandolo a un fichero .txt
      run: echo "${{ secrets.SECRETO }}" > secreto.txt

    - name: Print SECRETO # Leyendo el fichero secreto.txt   
      run:  cat secreto.txt      

    - name: Variables # trabajando con variables a nivel de repositorio    
      run:  echo "Hola, ${{ vars.NAME }}"    

    - name: Variables  y concatenenado # trabajando con variables a nivel de repositorio  y concateneando   
      run:  echo "Hola, Señor ${{ vars.NAME }} Buenas tardes" 
    
  job4: 
    needs: job1
    environment: Develop
    runs-on: ubuntu-latest 
    steps: 
    - name: Variables Enviroment # A pesar que a nivel de enviroment tiene el mismo nombre de variable toma el del enviroment   
      run:  echo "Hola, ${{ vars.NAME }}"  
    
    - name: Echo SECRETOS # trabajando con secretos a nivel de repositorio y enviandolo a un fichero .txt
      run: echo "${{ secrets.SECRETO }}" > secreto.txt

    - name: Print SECRETO # Leyendo el fichero secreto.txt   
      run:  cat secreto.txt      

  job5: 
    needs: job1
    environment: Production
    runs-on: ubuntu-latest 
    steps:    
    - name: Variables Enviroment # A pesar que a nivel de enviroment tiene el mismo nombre de variable toma el del enviroment    
      run:  echo "Hola, ${{ vars.NAME }}" 
      
    - name: Echo SECRETOS # trabajando con secretos a nivel de repositorio y enviandolo a un fichero .txt
      run: echo "${{ secrets.SECRETO }}" > secreto.txt

    - name: Print SECRETO # Leyendo el fichero secreto.txt   
      run:  cat secreto.txt    
  job6: 
    needs: job1
    environment: ${{ github.ref_name == 'main' && 'Production' || 'Develop' }} # Esto es un IF, remplaza el job 4 y 5 en un solo codigo
    runs-on: ubuntu-latest 
    steps:    
    - name: Variables Enviroment # A pesar que a nivel de enviroment tiene el mismo nombre de variable toma el del enviroment    
      run:  echo "Hola, ${{ vars.NAME }}" 
      
    - name: Echo SECRETOS # trabajando con secretos a nivel de repositorio y enviandolo a un fichero .txt
      run: echo "${{ secrets.SECRETO }}" > secreto.txt

    - name: Print SECRETO # Leyendo el fichero secreto.txt   
      run:  cat secreto.txt     
  
   